# Generated by Django 5.2.5 on 2025-09-06 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42cc97ef-f72b-40ce-9cc9-d97e61e33077'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42cc97ef-f72b-40ce-9cc9-d97e61e33077'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
