# Generated by Django 5.2.5 on 2025-09-06 04:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a41365f-6281-45c6-8231-b7e4c19aa8b3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a41365f-6281-45c6-8231-b7e4c19aa8b3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
